### ISSUE TITLE
undefined reference to `subunit_test_start'

### ISSUE THREAD

**Issue by MichaelFromSH** [Xilinx-CNS/solarcapture#2]
/usr/bin/ld: /lib/x86_64-linux-gnu/libcheck.a(check_log.o): in function `subunit_lfun':
(.text+0x61f): undefined reference to `subunit_test_start'
/usr/bin/ld: (.text+0x637): undefined reference to `subunit_test_pass'
/usr/bin/ld: (.text+0x64f): undefined reference to `subunit_test_error'
/usr/bin/ld: (.text+0x667): undefined reference to `subunit_test_fail'

My OS is ubuntu 22.04,How to fix it?

**Comment by abrunnin-xilinx** [comment]
Are you building unit tests?

One suspicion - from Ubuntu bug reports, it looks like they changed linker options (again) and you may need to add -lsubunit  (Probably to the line "LIBCHECK := -lcheck" in the Makefile.

**Comment by abrunnin-xilinx** [comment]
Oh, it might be simpler than that - do you have the 'check' package installed?  "sudo apt-get install check" on my test system got me past that error.
Although I'm now hitting a completely different error.   Support for other distributions than RHEL8 is a work in progress at this point.

**Comment by abrunnin-xilinx** [comment]
Following on from this - there is definitely a problem with building on Ubuntu.  The issue is twofold:
First, it tries to use auto configure for libpcap-sfsfc prior to having an libsolarcapture1.so which is a dependency.  Not sure why the makefile is doing that, but it should be fixable.  But even if you do provide that, the configure command still fails, saying it's unable to link to the symbols it is checking for.  Currently, I don't know why that is.

**Comment by abrunnin-xilinx** [comment]
Work in progress to fix this up, and to add a couple more tests to the number run by "make run"

**Comment by abrunnin-xilinx** [comment]
Should now be able to fully compile on Ubuntu.
